### PR TITLE
vyos: Add minimum ansible version check

### PR DESCRIPTION
**Pull request by NilashishC**

### CODE REVIEW

**Comment by pabelanger** [comment]
give me a moment to push up a fix for zuul, we've changed some things around for images over the last few days.

**Comment by NilashishC** [comment]
> give me a moment to push up a fix for zuul, we've changed some things around for images over the last few days.

Sure @pabelanger !

**Comment by pabelanger** [comment]
https://github.com/ansible-network/vyos/pull/20 is the fix, if you'd like to review

**Comment by NilashishC** [comment]
recheck

**Pull request merged**
